"""Compare BA point caps and graph densities on one cached local sequence.

This is a local diagnostic tool. It caches detected stars and the complete,
unsampled matched-edge corpus so repeated cap/edge-set/sampling-seed solves do
not reload images or repeat feature extraction and matching.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import pickle
import time
from pathlib import Path
from typing import Any

import cv2
import numpy as np
from loguru import logger

from tools.debug.debug_norma_ba import _camera_payload, _read_exif
from hoshicore.component.dataloader import load_img
from hoshicore.component.norma.bundle import (
    BundleAdjustmentError,
    BundleFrame,
    _build_edges,
    _connected_component,
    _edge_residuals,
    _sample_edge_pairs,
    _solve_bundle_parameters,
)
from hoshicore.component.norma.detection import detect_star_points
from hoshicore.component.norma.frame_align import (
    CameraInitializationPolicy,
    build_camera_candidate,
)
from hoshicore.component.norma.geometry_view import to_gray_f64
from hoshicore.component.norma.intrinsics_from_exif import lens_type_from_exif
from hoshicore.component.norma.optimization import CameraOptimizationPolicy


_CACHE_VERSION = 1


def _csv_ints(value: str) -> tuple[int, ...]:
    values = tuple(int(item.strip()) for item in value.split(",") if item.strip())
    if not values:
        raise argparse.ArgumentTypeError("expected comma-separated integers")
    return values


def _edge_sets(value: str) -> tuple[tuple[int, ...], ...]:
    result = []
    for group in value.split(";"):
        offsets = tuple(sorted({item for item in _csv_ints(group) if item > 0}))
        if not offsets:
            raise argparse.ArgumentTypeError("edge offsets must be positive")
        result.append(offsets)
    return tuple(dict.fromkeys(result))


def _args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("input_dir", type=Path)
    parser.add_argument("--mask", type=Path)
    parser.add_argument("--reference-index", type=int, required=True)
    parser.add_argument("--caps", type=_csv_ints, default=(64, 96, 128, 256, 512))
    parser.add_argument("--edge-sets", type=_edge_sets,
                        default=((1,), (1, 2), (1, 2, 4)))
    parser.add_argument("--sampling-seeds", type=_csv_ints, default=(0, 1, 2))
    parser.add_argument("--matching-seed", type=int, default=0)
    parser.add_argument("--max-nfev", type=int, default=300)
    parser.add_argument("--max-images", type=int)
    parser.add_argument("--fallback-focal-equiv-mm", type=float, default=20.0)
    parser.add_argument("--optimize-principal-point",
                        action=argparse.BooleanOptionalAction, default=None)
    parser.add_argument("--allow-large-principal-point-offset",
                        action="store_true")
    parser.add_argument("--cache-dir", type=Path,
                        default=Path("benchmark_results/ba_sampling_cache"))
    parser.add_argument("--refresh-cache", action="store_true")
    parser.add_argument("--prepare-cache-only", action="store_true",
                        help="Detect stars and build the full edge cache, then exit")
    parser.add_argument("--output", type=Path,
                        default=Path("benchmark_results/ba_sampling.json"))
    return parser.parse_args()


def _image_paths(folder: Path, max_images: int | None) -> list[Path]:
    suffixes = {".tif", ".tiff", ".jpg", ".jpeg", ".png"}
    paths = sorted(path for path in folder.iterdir()
                   if path.is_file() and path.suffix.lower() in suffixes)
    return paths if max_images is None else paths[:max_images]


def _masked(image: np.ndarray, mask: np.ndarray | None) -> np.ndarray:
    if mask is None:
        return image
    runtime = mask
    if runtime.ndim == 2 and image.ndim == 3:
        runtime = np.repeat(runtime[..., None], image.shape[2], axis=-1)
    runtime = cv2.resize(
        runtime.astype(np.float32), (image.shape[1], image.shape[0]),
        interpolation=cv2.INTER_NEAREST) > 0.5
    return np.multiply(image, runtime)


def _file_signature(path: Path) -> dict[str, Any]:
    stat = path.stat()
    return {"path": str(path.resolve()), "size": stat.st_size,
            "mtime_ns": stat.st_mtime_ns}


def _digest(value: Any) -> str:
    return hashlib.sha256(pickle.dumps(value, protocol=5)).hexdigest()[:20]


def _load_cache(path: Path) -> Any | None:
    if not path.exists():
        return None
    # The cache is local debug data generated by this tool; do not load cache
    # files obtained from an untrusted source because pickle is executable.
    with path.open("rb") as handle:
        payload = pickle.load(handle)
    if payload.get("version") != _CACHE_VERSION:
        return None
    return payload["value"]


def _write_cache(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("wb") as handle:
        pickle.dump({"version": _CACHE_VERSION, "value": value},
                    handle, protocol=5)
    for attempt in range(5):
        try:
            temporary.replace(path)
            return
        except PermissionError:
            if attempt == 4:
                raise
            time.sleep(0.1 * (attempt + 1))


def _load_or_detect(paths: list[Path], mask_path: Path | None,
                    cache_dir: Path, refresh: bool):
    signature = {
        "files": [_file_signature(path) for path in paths],
        "mask": _file_signature(mask_path) if mask_path else None,
        "detector": "detect_star_points",
    }
    cache_path = cache_dir / f"stars-{_digest(signature)}.pkl"
    cached = None if refresh else _load_cache(cache_path)
    if cached is not None and len(cached) == len(paths):
        return cached, cache_path, True, 0.0

    mask = load_img(str(mask_path)) if mask_path else None
    started = time.perf_counter()
    observations = [] if cached is None else list(cached)
    for index, path in enumerate(paths[len(observations):], len(observations)):
        print(f"detect [{index + 1}/{len(paths)}] {path.name}", flush=True)
        image = load_img(str(path))
        stars = detect_star_points(to_gray_f64(_masked(image, mask)))
        observations.append((index, stars, image.shape, _read_exif(path)))
        _write_cache(cache_path, observations)
    elapsed = time.perf_counter() - started
    return observations, cache_path, False, elapsed


def _load_or_build_edges(frames, union_offsets, matching_seed, candidate,
                         stars_cache: Path, cache_dir: Path, refresh: bool):
    signature = {
        "stars_cache": stars_cache.name,
        "union_offsets": union_offsets,
        "matching_seed": matching_seed,
        "candidate": candidate,
    }
    cache_path = cache_dir / f"edges-{_digest(signature)}.pkl"
    cached = None if refresh else _load_cache(cache_path)
    if cached is not None:
        return cached[0], cached[1], cache_path, True, 0.0
    started = time.perf_counter()
    edges, sequence_scale = _build_edges(
        frames, union_offsets, matching_seed, max_pairs_per_edge=None)
    elapsed = time.perf_counter() - started
    _write_cache(cache_path, (edges, sequence_scale))
    return edges, sequence_scale, cache_path, False, elapsed


def _sample_edges(edges, cap: int, width: int, height: int, seed: int):
    return [
        _sample_edge_pairs(
            edge, cap, width, height,
            (seed + edge.first_index * 1009
             + edge.second_index * 9176) % (2 ** 32))
        for edge in edges
    ]


def _rotation_difference_deg(first: np.ndarray, second: np.ndarray) -> float:
    cosine = np.clip((np.trace(first @ second.T) - 1.0) / 2.0, -1.0, 1.0)
    return math.degrees(math.acos(float(cosine)))


def _summary(values) -> dict[str, float]:
    array = np.asarray(values, dtype=np.float64)
    return {"median": float(np.median(array)),
            "p90": float(np.percentile(array, 90)),
            "max": float(np.max(array))}


def _full_residual_summary(edges, rotations, camera) -> dict[str, float | int]:
    values = [_edge_residuals(edge, rotations, camera) for edge in edges
              if edge.first_index in rotations and edge.second_index in rotations]
    if not values:
        return {"evaluated_pairs": 0}
    residuals = np.concatenate(values)
    edge_p90 = np.asarray([np.percentile(value, 90) for value in values])
    return {
        "evaluated_pairs": int(sum(len(value) for value in values)),
        "point_p50_deg": math.degrees(float(np.percentile(residuals, 50))),
        "point_p90_deg": math.degrees(float(np.percentile(residuals, 90))),
        "point_p99_deg": math.degrees(float(np.percentile(residuals, 99))),
        "edge_p90_median_deg": math.degrees(float(np.median(edge_p90))),
        "edge_p90_max_deg": math.degrees(float(np.max(edge_p90))),
    }


def _camera_delta(camera, reference) -> dict[str, float]:
    current = np.asarray(camera.distortion.to_cv2(), dtype=np.float64)
    baseline = np.asarray(reference.distortion.to_cv2(), dtype=np.float64)
    difference = current - baseline
    return {
        "focal_relative": float(
            camera.intrinsics.focal_length_mm
            / reference.intrinsics.focal_length_mm - 1.0),
        "distortion_l2": float(np.linalg.norm(difference)),
        "distortion_max_abs": float(np.max(np.abs(difference))),
    }


def main() -> int:
    args = _args()
    logger.remove()
    paths = _image_paths(args.input_dir, args.max_images)
    if not paths:
        raise ValueError("input directory contains no supported images")
    if not 0 <= args.reference_index < len(paths):
        raise ValueError("reference index is outside the discovered sequence")
    args.cache_dir.mkdir(parents=True, exist_ok=True)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    started = time.perf_counter()

    observations, stars_cache, stars_cache_hit, detection_seconds = (
        _load_or_detect(paths, args.mask, args.cache_dir, args.refresh_cache))
    _, _, shape, reference_tags = observations[args.reference_index]
    policy = CameraInitializationPolicy(
        lens_type=lens_type_from_exif(reference_tags),
        fallback_focal_equiv_mm=args.fallback_focal_equiv_mm,
        optimize_focal=True, optimize_distortion=True,
        optimize_principal_point=args.optimize_principal_point,
        allow_large_principal_point_offset=(
            args.allow_large_principal_point_offset))
    candidate = build_camera_candidate(
        reference_tags, shape, "distortion", init_policy=policy)
    frames = [BundleFrame(index, stars, candidate)
              for index, stars, _, _ in observations]

    union_offsets = tuple(sorted({offset for group in args.edge_sets
                                  for offset in group}))
    edges, sequence_scale, edge_cache, edge_cache_hit, edge_seconds = (
        _load_or_build_edges(
            frames, union_offsets, args.matching_seed, candidate,
            stars_cache, args.cache_dir, args.refresh_cache))
    successful = [edge for edge in edges if edge.error is None]
    camera = candidate.camera.with_focal_length(
        candidate.camera.intrinsics.focal_length_mm * sequence_scale)
    requested = candidate.optimization_policy
    focal_only = CameraOptimizationPolicy(True, False, False, 0)

    report = {
        "input_dir": str(args.input_dir), "files": len(paths),
        "reference_index": args.reference_index,
        "caps": list(args.caps),
        "edge_sets": [list(group) for group in args.edge_sets],
        "sampling_seeds": list(args.sampling_seeds),
        "matching_seed": args.matching_seed,
        "union_offsets": list(union_offsets),
        "union_successful_edge_count": len(successful),
        "union_full_pair_count": int(sum(len(edge.first_pts)
                                         for edge in successful)),
        "cache": {
            "stars": str(stars_cache), "stars_hit": stars_cache_hit,
            "edges": str(edge_cache), "edges_hit": edge_cache_hit,
        },
        "timings_seconds": {
            "detect": detection_seconds, "build_edges": edge_seconds},
        "results": [],
    }
    if args.prepare_cache_only:
        report["timings_seconds"]["total"] = time.perf_counter() - started
        args.output.write_text(json.dumps(
            report, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"cache prepared: {edge_cache.resolve()}")
        return 0
    solved_by_key = {}
    for edge_set in args.edge_sets:
        selected = [edge for edge in successful
                    if edge.second_index - edge.first_index in edge_set]
        component = _connected_component(selected, args.reference_index)
        selected = [edge for edge in selected
                    if edge.first_index in component
                    and edge.second_index in component]
        for cap in args.caps:
            for seed in args.sampling_seeds:
                sampled = _sample_edges(
                    selected, cap, shape[1], shape[0], seed)
                solve_started = time.perf_counter()
                camera_mode = "requested"
                reason = None
                try:
                    solved_camera, rotations, retained, condition = (
                        _solve_bundle_parameters(
                            sampled, args.reference_index, component, camera,
                            requested, args.max_nfev))
                    solved_policy = requested
                except BundleAdjustmentError as exc:
                    camera_mode = "focal_fallback"
                    reason = str(exc)
                    try:
                        solved_camera, rotations, retained, condition = (
                            _solve_bundle_parameters(
                                sampled, args.reference_index, component,
                                camera, focal_only, args.max_nfev))
                        solved_policy = focal_only
                    except BundleAdjustmentError as fallback_exc:
                        row = {
                            "status": "failed",
                            "edge_offsets": list(edge_set), "cap": cap,
                            "sampling_seed": seed,
                            "graph_frames": len(component),
                            "full_edges": len(selected),
                            "full_pairs": int(sum(len(edge.first_pts)
                                                  for edge in selected)),
                            "sampled_pairs": int(sum(len(edge.first_pts)
                                                     for edge in sampled)),
                            "solve_seconds": time.perf_counter() - solve_started,
                            "requested_error": reason,
                            "fallback_error": str(fallback_exc),
                        }
                        report["results"].append(row)
                        args.output.write_text(json.dumps(
                            report, indent=2, ensure_ascii=False),
                            encoding="utf-8")
                        print(json.dumps(row, indent=2, ensure_ascii=False),
                              flush=True)
                        continue
                solve_seconds = time.perf_counter() - solve_started
                key = (edge_set, cap, seed)
                solved_by_key[key] = (solved_camera, rotations)
                row = {
                    "status": "ok",
                    "edge_offsets": list(edge_set), "cap": cap,
                    "sampling_seed": seed,
                    "graph_frames": len(component),
                    "full_edges": len(selected),
                    "full_pairs": int(sum(len(edge.first_pts)
                                          for edge in selected)),
                    "sampled_pairs": int(sum(len(edge.first_pts)
                                             for edge in sampled)),
                    "retained_edges": len(retained),
                    "solve_seconds": solve_seconds,
                    "camera_solve_mode": camera_mode,
                    "camera_fallback_reason": reason,
                    "active_camera_parameter_count": (
                        1 if solved_policy == focal_only else
                        1 + requested.n_dist
                        + (2 if requested.optimize_principal_point else 0)),
                    "observability_condition": condition,
                    "camera": _camera_payload(solved_camera),
                    "selected_graph_full_residual": _full_residual_summary(
                        selected, rotations, solved_camera),
                    "union_graph_full_residual": _full_residual_summary(
                        successful, rotations, solved_camera),
                }
                report["results"].append(row)
                args.output.write_text(json.dumps(
                    report, indent=2, ensure_ascii=False), encoding="utf-8")
                print(json.dumps(row, indent=2, ensure_ascii=False), flush=True)

    if not solved_by_key:
        report["timings_seconds"]["total"] = time.perf_counter() - started
        args.output.write_text(json.dumps(
            report, indent=2, ensure_ascii=False), encoding="utf-8")
        raise BundleAdjustmentError("all sampling experiment combinations failed")
    reference_key = max(
        solved_by_key,
        key=lambda item: (
            len(item[0]), item[1],
            -args.sampling_seeds.index(item[2]), item[0]))
    reference_edge_set, reference_cap, reference_seed = reference_key
    reference_camera, reference_rotations = solved_by_key[reference_key]
    for row in report["results"]:
        if row["status"] != "ok":
            continue
        key = (tuple(row["edge_offsets"]), row["cap"], row["sampling_seed"])
        solved_camera, rotations = solved_by_key[key]
        common = sorted(set(rotations) & set(reference_rotations))
        row["camera_delta_vs_reference"] = _camera_delta(
            solved_camera, reference_camera)
        row["rotation_delta_vs_reference_deg"] = _summary([
            _rotation_difference_deg(rotations[index],
                                     reference_rotations[index])
            for index in common
        ])
    report["reference"] = {
        "edge_offsets": list(reference_edge_set),
        "cap": reference_cap, "sampling_seed": reference_seed,
    }
    report["timings_seconds"]["total"] = time.perf_counter() - started
    args.output.write_text(json.dumps(
        report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"report: {args.output.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
